import type { ComprehensiveTable } from "./comprehensiveTable";

/**
 * Comparative post-GW newsletter — a plain-text, shareable write-up of a
 * completed gameweek, built purely from the DGH ledger already computed by
 * comprehensiveTable.ts. No new data source: same ledger the League tab reads.
 */

export function buildGwNewsletter(input: {
  table: ComprehensiveTable;
  gameweek: number;
  myEntryId: number | null;
  leagueLabel?: string;
}): string {
  const { table, gameweek, myEntryId, leagueLabel = "DGH Mini-League" } = input;

  const rowsThisGw = table.managers
    .map((m) => ({ m, row: m.gwRows.find((r) => r.event === gameweek) ?? null }))
    .filter((x): x is { m: (typeof table.managers)[number]; row: NonNullable<(typeof table.managers)[number]["gwRows"][number]> } => x.row !== null);

  if (!rowsThisGw.length) {
    return `No DGH ledger data for GW${gameweek} yet. Sync the league ledger from the League tab, then generate the newsletter again.`;
  }

  const byGwDesc = [...rowsThisGw].sort((a, b) => b.row.gwAdjusted - a.row.gwAdjusted);
  const winner = byGwDesc[0];
  const last = byGwDesc[byGwDesc.length - 1];
  const me = myEntryId !== null ? rowsThisGw.find((x) => x.m.entryId === myEntryId) : undefined;
  const biggestHitter = [...rowsThisGw].sort((a, b) => b.row.transferHits - a.row.transferHits)[0];
  const chipUsers = rowsThisGw.filter((x) => x.row.activeChip);

  const lines: string[] = [];
  lines.push(`${leagueLabel.toUpperCase()} — GW${gameweek} RECAP`);
  lines.push("");
  lines.push(`GW WINNER: ${winner.m.teamName} (${winner.m.managerName}) — ${winner.row.gwAdjusted} pts`);
  if (byGwDesc.length > 1) {
    const second = byGwDesc[1];
    const margin = winner.row.gwAdjusted - second.row.gwAdjusted;
    lines.push(`   Won by ${margin} pt${margin === 1 ? "" : "s"} over ${second.m.teamName}`);
  }
  lines.push("");
  lines.push(`BOTTOM OF THE TABLE: ${last.m.teamName} — ${last.row.gwAdjusted} pts${last.row.relegationFine ? " (relegation fine applied)" : ""}`);
  lines.push("");
  if (me) {
    lines.push(`YOUR RESULT: ${me.row.gwAdjusted} pts · GW rank #${me.row.gwRank} of ${rowsThisGw.length} · season total ${me.m.overallPoints} pts (#${me.m.overallRank} overall)`);
    lines.push("");
  }
  if (biggestHitter.row.transferHits > 0) {
    lines.push(`BIGGEST GAMBLE: ${biggestHitter.m.teamName} took a -${biggestHitter.row.transferHits} pt hit`);
    lines.push("");
  }
  if (chipUsers.length) {
    lines.push(`CHIPS PLAYED: ${chipUsers.map((x) => `${x.m.teamName} (${x.row.activeChip})`).join(", ")}`);
    lines.push("");
  }
  lines.push("SEASON STANDINGS — TOP 5 (DGH ADJUSTED)");
  const top5 = [...table.managers].sort((a, b) => a.overallRank - b.overallRank).slice(0, 5);
  top5.forEach((m, i) => {
    lines.push(`${i + 1}. ${m.teamName} — ${m.overallPoints} pts (${m.wins}W · ${m.podiums} podiums)`);
  });
  lines.push("");
  lines.push(`Generated by DGH FPL Manager · ${new Date().toLocaleDateString()}`);

  return lines.join("\n");
}
