import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, View } from "react-native";
import { useTheme } from "../hooks/useTheme";
import { useWarRoomData } from "../hooks/useWarRoomData";
import { Page, Header, Hero, Metric, Surface, Section, Pill, Row } from "../components/Premium";
import { fetchRankPointsLadder, fetchTop10kStandings, fetchManagerSnapshots, computeCohortAnalytics, buildWeeklyAwardsTaxonomy, whyThisHappened, buildCloneReport, fetchPopularTransfers, buildPositionRatings, buildClubContribution } from "../lib/analytics/fplWideIntelligence";
import { SquadDnaPitch } from "../components/SquadDnaPitch";
import type { ManagerSnapshot } from "../lib/analytics/fplWideIntelligence";

export default function FplWideScreen(){
 const {theme}=useTheme(); const {data}=useWarRoomData(); const [busy,setBusy]=useState(""); const [ladder,setLadder]=useState<any[]>([]); const [cohort,setCohort]=useState<ReturnType<typeof computeCohortAnalytics>|null>(null); const [snapshots,setSnapshots]=useState<ManagerSnapshot[]>([]); const [progress,setProgress]=useState(0); const [transferProgress,setTransferProgress]=useState(0); const [popularTransfers,setPopularTransfers]=useState<any[]>([]);
 const runLadder=async()=>{setBusy("ladder");try{setLadder(await fetchRankPointsLadder())}finally{setBusy("")}};
 const runCohort=async()=>{if(!data)return;setBusy("cohort");setProgress(0);try{const rows=await fetchTop10kStandings();const snaps=await fetchManagerSnapshots(rows,false,(d,t)=>setProgress(Math.round(d/t*100)));const playerTeam=Object.fromEntries(data.bootstrap.elements.map(p=>[p.id,p.team]));setSnapshots(snaps);setCohort(computeCohortAnalytics(snaps,data.mySquad.filter(p=>p.isXI).map(p=>p.playerId),playerTeam))}finally{setBusy("")}};
 const runTransfers=async()=>{if(!snapshots.length||!data)return;setBusy("transfers");setTransferProgress(0);try{const names=Object.fromEntries(data.bootstrap.elements.map(p=>[p.id,p.web_name]));setPopularTransfers(await fetchPopularTransfers(snapshots,names,data.gameweek,false,(d,t)=>setTransferProgress(Math.round(d/t*100))))}finally{setBusy("")}};
 const positionRatings=useMemo(()=>cohort&&data?buildPositionRatings(data.mySquad.filter(p=>p.isXI).map(p=>({playerId:p.playerId,position:p.player.position})),snapshots,Object.fromEntries(data.bootstrap.elements.map(p=>[p.id,{element_type:p.element_type}])),Object.fromEntries(data.bootstrap.element_types.map(t=>[t.id,t.singular_name_short]))):{},[cohort,data,snapshots]);
 const clubContribution=useMemo(()=>cohort&&data?buildClubContribution({snapshots,playerClubById:Object.fromEntries(data.bootstrap.elements.map(p=>[p.id,p.team])),livePointsByPlayer:Object.fromEntries(data.liveResponse?.elements.map(e=>[e.id,e.stats.total_points])??[]),myXiIds:data.mySquad.filter(p=>p.isXI).map(p=>p.playerId)}):{},[cohort,data,snapshots]);
 const cloneReport=useMemo(()=>cohort&&data?buildCloneReport(snapshots,data.mySquad.filter(p=>p.isXI).map(p=>p.playerId)):null,[cohort,snapshots,data]);
 const topOwners=useMemo(()=>cohort?Object.entries(cohort.ownership).sort((a,b)=>b[1]-a[1]).slice(0,10):[],[cohort]); const topCaps=useMemo(()=>cohort?Object.entries(cohort.captaincy).sort((a,b)=>b[1]-a[1]).slice(0,8):[],[cohort]);
 const awards=data?buildWeeklyAwardsTaxonomy({gw:data.gameweek,rank:data.myRow?.rank??0,gwPoints:data.myRow?.event_total??0,previousRank:data.myRow?.last_rank??data.myRow?.rank??0,transfers:data.currentTransferHits??0,captainPoints:data.mySquad.find(p=>p.isCaptain)?.livePoints??0,chip:data.activeChip}):null;
 const narrative=data?whyThisHappened({rankDelta:(data.myRow?.last_rank??0)-(data.myRow?.rank??0),captainDelta:0,differentialDelta:0,templateDelta:0}):null;
 return <Page><Header eyebrow="FPL-WIDE INTELLIGENCE" title="Cohort Lab" subtitle="Top-10K benchmarking, rank ladder, clones, transfers and DGH-wide signals"/>
 <Hero variant="navy"><View style={{flexDirection:"row",gap:12}}><Metric label="Top-10K" value={cohort?String(cohort.sampleSize):"—"} onHero/><Metric label="Managers fetched" value={cohort?String(cohort.fetchedManagers):"—"} onHero/><Metric label="Snapshots" value={String(snapshots.length)} onHero/></View><Text style={{color:"rgba(255,255,255,.75)",fontSize:10,marginTop:10}}>Full-cohort mode is deliberately explicit: the Top-10K squad reconstruction can require thousands of manager-level requests and should run only when you choose it.</Text></Hero>
 <Section title="Rank → points ladder"/><Surface><Text style={{color:theme.muted,fontSize:10}}>Nine independent page-jump requests: 1 / 100 / 1K / 5K / 10K / 50K / 100K / 300K / 1M.</Text><Pressable onPress={()=>void runLadder()} disabled={!!busy} style={{marginTop:10,minHeight:42,borderRadius:12,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center"}}>{busy==="ladder"?<ActivityIndicator color={theme.background}/>:<Text style={{color:theme.background,fontWeight:"900"}}>LOAD LADDER</Text>}</Pressable>{ladder.map(x=><Row key={x.targetRank} label={`Rank ${x.targetRank.toLocaleString()}`} value={`${x.points.toLocaleString()} pts · sampled #${x.sampledRank.toLocaleString()}`}/>)}</Surface>
 <Section title="Top-10K cohort sampler"/><Surface><Text style={{color:theme.muted,fontSize:10,lineHeight:15}}>Collects full current-GW squads, captaincy, formations and active chips from the official overall league. Private/inaccessible entries are skipped and never fabricated.</Text>{busy==="cohort"?<><Text style={{color:theme.primary,fontWeight:"900",fontSize:16,marginTop:12}}>{progress}%</Text><Text style={{color:theme.muted,fontSize:9}}>manager snapshots processed</Text></>:<Pressable onPress={()=>void runCohort()} disabled={!data||!!busy} style={{marginTop:10,minHeight:42,borderRadius:12,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center"}}><Text style={{color:theme.background,fontWeight:"900"}}>RUN TOP-10K SAMPLER</Text></Pressable>}</Surface>
 {cohort?<>
 <Section title="Cohort ownership / captaincy"/><Surface><Text style={{color:theme.foreground,fontWeight:"900",fontSize:13}}>Most-owned XI players</Text>{topOwners.map(([id,count])=><Row key={id} label={`Player #${id}`} value={`${(Number(count)/cohort.sampleSize*100).toFixed(1)}%`}/>)}<Text style={{color:theme.foreground,fontWeight:"900",fontSize:13,marginTop:12}}>Captaincy leaders</Text>{topCaps.map(([id,count])=><Row key={id} label={`Player #${id}`} value={`${(Number(count)/cohort.sampleSize*100).toFixed(1)}%`}/>)}</Surface>
 <Section title="Clone detector"/><Surface>{cohort.cloneSignatures.slice(0,10).map((c,i)=><View key={c.signature} style={{paddingVertical:8,borderBottomWidth:1,borderBottomColor:theme.border}}><View style={{flexDirection:"row",justifyContent:"space-between"}}><Text style={{color:theme.foreground,fontWeight:"800",fontSize:11}}>Clone #{i+1}{c.mine?" · YOUR XI":""}</Text><Pill label={`${c.count} managers`} tone={c.mine?"warning":"neutral"}/></View><Text style={{color:theme.muted,fontSize:8,marginTop:3}}>{c.signature}</Text></View>)}</Surface>
 <Section title="Formation distribution"/><Surface>{Object.entries(cohort.formations).sort((a,b)=>b[1]-a[1]).map(([k,v])=><Row key={k} label={k} value={`${(Number(v)/cohort.sampleSize*100).toFixed(1)}%`}/>)}</Surface>
 </>:null}
 <Section title="Team ratings by position"/><Surface>{Object.entries(positionRatings).map(([pos,v])=><Row key={pos} label={pos} value={`${v.mine.toFixed(1)} vs ${v.sampleAverage.toFixed(1)} sample · ${v.delta>=0?"+":""}${v.delta.toFixed(1)}`} />)}</Surface>
 <Section title="PL Club Contribution"/><Surface>{Object.entries(clubContribution).sort((a,b)=>b[1].delta-a[1].delta).slice(0,12).map(([club,v])=><Row key={club} label={`Club #${club}`} value={`${v.minePoints.toFixed(1)} vs ${v.sampleAverage.toFixed(1)} · ${v.delta>=0?"+":""}${v.delta.toFixed(1)}`} />)}</Surface>
 <Section title="FPL-wide clone / cohort intelligence"/><Surface>{cloneReport?<><Row label="Exact clones of your XI" value={`${cloneReport.exactCloneCount} (${cloneReport.exactClonePct.toFixed(2)}%)`} /><Row label="Highest XI overlap" value={`${cloneReport.highestOverlap}/11 players`} /></>:<Text style={{color:theme.muted,fontSize:10}}>Run the sampler first.</Text>}<Text style={{color:theme.foreground,fontWeight:"900",fontSize:12,marginTop:10}}>Your pitch</Text>{data?<SquadDnaPitch squad={data.mySquad}/>:null}</Surface>
 <Section title="Popular Transfers — actual GW moves"/><Surface><Text style={{color:theme.muted,fontSize:10}}>Only transfers recorded for GW{data?.gameweek ?? "—"} are counted.</Text>{busy==="transfers"?<Text style={{color:theme.primary,fontWeight:"900",marginTop:8}}>{transferProgress}% processed</Text>:<Pressable disabled={!snapshots.length||!!busy} onPress={()=>void runTransfers()} style={{marginTop:9,minHeight:40,borderRadius:11,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center"}}><Text style={{color:theme.background,fontWeight:"900"}}>LOAD TRANSFER LEADERBOARD</Text></Pressable>}{popularTransfers.slice(0,15).map((x,i)=><Row key={x.playerId} label={`${i+1}. ${x.playerName}`} value={`${x.transfers} transfers · ${x.adoptionPct.toFixed(1)}%`} />)}</Surface>
 <Section title="Weekly Awards taxonomy"/><Surface>{awards&&Object.entries(awards).map(([k,v])=><View key={k} style={{flexDirection:"row",justifyContent:"space-between",paddingVertical:6}}><Text style={{color:theme.foreground,fontSize:11,fontWeight:"700"}}>{k}</Text><Pill label={v?"EARNED":"—"} tone={v?"success":"neutral"}/></View>)}</Surface>
 <Section title="Why This Happened"/><Surface>{narrative?<><Text style={{color:theme.foreground,fontWeight:"900",fontSize:14}}>{narrative.headline}</Text>{narrative.gains.map(x=><Text key={x} style={{color:theme.success,fontSize:10,marginTop:6}}>+ {x}</Text>)}{narrative.losses.map(x=><Text key={x} style={{color:theme.error,fontSize:10,marginTop:6}}>− {x}</Text>)}</>:<Text style={{color:theme.muted,fontSize:10}}>Load War Room data to generate the post-GW narrative.</Text>}</Surface>
 <Surface style={{backgroundColor:theme.surfaceAlt}}><Text style={{color:theme.foreground,fontWeight:"900",fontSize:12}}>Badge / tag / pitch / DNA layer</Text><Text style={{color:theme.muted,fontSize:10,lineHeight:15,marginTop:5}}>Cohort mode exposes the data needed by the UI badge system, pitch overlays and Squad-DNA visualizer. The existing Player DNA engine remains the source of player-level DNA signals.</Text></Surface>
 </Page>
}
