import { useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { router } from "expo-router";
import Constants from "expo-constants";
import { useTheme } from "../../hooks/useTheme";
import { useWarRoomData } from "../../hooks/useWarRoomData";
import { LEAGUE_ID, MY_ENTRY_ID } from "../../lib/config";
import { exportStandings, exportSquad, exportOpponentSquads, exportOwnershipMap, exportTransferSimulations } from "../../lib/export";
import { buildTransferScenarios, buildRivalImpacts } from "../../lib/analytics/transferEngine";
import { optimizeXI } from "../../lib/analytics/xiOptimizer";
import { projectNextGw } from "../../lib/analytics/projection";
import { LoadingShell, ErrorBlock, FreshnessBanner } from "../../components/StatusStates";
import { Page, Header, Surface, Section, Pill, IconButton, Shortcut } from "../../components/Premium";
export default function MoreScreen(){const{theme}=useTheme();const{data,isLoading,isError,error,refetch,fullUpdate}=useWarRoomData();const[format,setFormat]=useState<"csv"|"json">("csv");const[busy,setBusy]=useState("");const[refreshing,setRefreshing]=useState(false);if(isLoading)return <LoadingShell label="Loading settings…"/>;if(isError||!data)return <ErrorBlock message={String((error as Error)?.message??"Data unavailable")} onRetry={()=>refetch()}/>;
 const doRefresh=async()=>{setRefreshing(true);try{await refetch()}finally{setRefreshing(false)}};
 const run=async(label:string,fn:()=>Promise<any>)=>{setBusy(label);try{await fn()}finally{setBusy("")}};
 return <Page refreshing={refreshing} onRefresh={()=>void doRefresh()}><Header eyebrow="CONTROL ROOM" title="More" subtitle="Tools, exports, configuration and data health" right={<IconButton icon="refresh" label="Refresh" onPress={()=>void refetch()}/>}/><FreshnessBanner stale={data.stale} fetchedAt={data.fetchedAt}/>
 <Section title="Quick access"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:16,paddingRight:6,paddingBottom:6}} style={{marginBottom:2}}>{[["DGH Spy","eye","#D9455F","/(tabs)/spy"],["Rivals","people",theme.primary,"/(tabs)/rivals"],["Squad","football",theme.accent,"/(tabs)/squad"],["Fixtures","calendar",theme.warning,"/(tabs)/fixtures"],["Ownership","pie-chart",theme.success,"/(tabs)/ownership"],["Chips","flash",theme.error,"/(tabs)/chips"],["Tools","construct","#D9A441","/(tabs)/tools"],["What-If","flask","#8E5CD9","/(tabs)/whatif"],["Forecast","stats-chart","#2E9E8C","/(tabs)/forecast"],["Compare","git-compare","#4C8BF5","/compare"],["Team Strength","bar-chart","#E0862F","/team-strength"], ["FPL-Wide","analytics","#4C8BF5","/fpl-wide"], ["Manager Lookup","search","#2E9E6B","/manager-lookup"]].map(([label,icon,color,href])=><Shortcut key={label as string} icon={icon as any} label={label as string} color={color as string} onPress={()=>router.push(href as any)}/>)}</ScrollView>
 <Section title="Run the league"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:16,paddingRight:6,paddingBottom:6}} style={{marginBottom:2}}>{[["League Settings","settings",theme.accent,"/league-settings"],["Awards","trophy","#D9A441","/awards"],["Newsletter","newspaper",theme.primary,"/newsletter"],["Domination Sheet","document-text","#8E5CD9","/domination-sheet"],["Template Team","people","#2E9E6B","/mini-league-template"],["Timelapse","trending-up","#E0862F","/timelapse"]].map(([label,icon,color,href])=><Shortcut key={label as string} icon={icon as any} label={label as string} color={color as string} onPress={()=>router.push(href as any)}/>)}</ScrollView>
 <Section title="Data health"/><Surface>{data.validation.checks.map(c=><View key={c.id} style={{flexDirection:"row",alignItems:"center",paddingVertical:7,borderBottomWidth:1,borderBottomColor:theme.border}}><View style={{flex:1}}><Text style={{color:theme.foreground,fontWeight:"700",fontSize:12}}>{c.label}</Text><Text style={{color:theme.muted,fontSize:9,marginTop:2}}>{c.detail}</Text></View><Pill label={c.passed?"PASS":"CHECK"} tone={c.passed?"success":"danger"}/></View>)}</Surface>
 <Section title="Export"/><Surface><Text style={{color:theme.muted,fontSize:11,marginBottom:10}}>Use exports for offline analysis. Current format: {format.toUpperCase()}</Text><View style={{flexDirection:"row",gap:8,marginBottom:12}}>{(["csv","json"] as const).map(f=><Pressable key={f} onPress={()=>setFormat(f)} style={{flex:1,minHeight:42,borderRadius:11,backgroundColor:f===format?theme.primary:theme.surfaceAlt,alignItems:"center",justifyContent:"center"}}><Text style={{color:f===format?theme.background:theme.foreground,fontWeight:"900"}}>{f.toUpperCase()}</Text></Pressable>)}</View><View style={{gap:8}}>{([["Standings",()=>exportStandings(data.standings,format)],["My squad",()=>exportSquad(data.mySquad,"my_squad",format)],["Rival squads",()=>exportOpponentSquads(data.rivals,format)],["Ownership",()=>exportOwnershipMap(data.ownership,format)],["Transfer models",()=>{const sc=buildTransferScenarios(data.mySquad,data.playerPool,data.bank,data.freeTransfers);const xi=optimizeXI(data.mySquad);const pts=xi.startingXI.reduce((s,p)=>s+projectNextGw(p.player),0)+(xi.captain?.projected??0);const imp=buildRivalImpacts(pts,data.myRow?.dghTotalPoints??data.myRow?.total??0,data.myRow?.dghRank??data.myRow?.rank??999,data.rivals);return exportTransferSimulations(sc,imp,format)}]] as [string,()=>Promise<any>][]).map(([label,fn])=><Pressable key={label as string} disabled={!!busy} onPress={()=>void run(label as string,fn as any)} style={{minHeight:44,borderRadius:12,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surfaceAlt,justifyContent:"center",paddingHorizontal:13}}><Text style={{color:theme.foreground,fontWeight:"800",fontSize:12}}>{busy===label?"EXPORTING…":label}</Text></Pressable>)}</View></Surface>
 <Section title="League configuration"/><Surface><View style={{flexDirection:"row",gap:12}}><View style={{flex:1}}><Text style={{color:theme.muted,fontSize:9,fontWeight:"800"}}>LEAGUE ID</Text><Text style={{color:theme.foreground,fontWeight:"900",marginTop:4}}>{LEAGUE_ID}</Text></View><View style={{flex:1}}><Text style={{color:theme.muted,fontSize:9,fontWeight:"800"}}>ENTRY ID</Text><Text style={{color:theme.foreground,fontWeight:"900",marginTop:4}}>{MY_ENTRY_ID}</Text></View><View style={{flex:1}}><Text style={{color:theme.muted,fontSize:9,fontWeight:"800"}}>GAMEWEEK</Text><Text style={{color:theme.foreground,fontWeight:"900",marginTop:4}}>{data.gameweek}</Text></View></View></Surface>
 <Pressable onPress={()=>void fullUpdate()} style={{minHeight:48,borderRadius:13,backgroundColor:theme.surfaceAlt,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:theme.border}}><Text style={{color:theme.error,fontWeight:"900",fontSize:11}}>REFRESH EVERYTHING</Text></Pressable><Text style={{color:theme.muted,fontSize:9,textAlign:"center",marginTop:12}}>DGH FPL Manager · v{Constants.expoConfig?.version ?? "3.2.2"}</Text>
 </Page>}
